// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BTT585.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211017095337_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("BTT585.Models.BTT2210", b =>
                {
                    b.Property<int>("BTTId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<string>("BTTGender")
                        .HasColumnType("TEXT");

                    b.Property<string>("BTTName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("BTTId");

                    b.ToTable("BTT2210");
                });
#pragma warning restore 612, 618
        }
    }
}
